# Enable the "Sponsor" button by uncommenting a platform below once configured.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# github: [Rinava]
# ko_fi: your_handle
# open_collective: your_project
